name: cudclusterplus
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  # Basic dependencies
  - python=3.9
  - pip
  - numpy>=1.20.0
  - matplotlib>=3.4.0
  - pandas>=1.3.0
  
  # Build tools
  - cmake>=3.18.0
  - ninja
  - pybind11>=2.9.0
  - setuptools>=58.0.0
  - wheel
  
  # CUDA dependencies
  - cudatoolkit>=11.2
  - cudatoolkit-dev>=11.2
  
  # C++ compiler
  - cxx-compiler
  
  # JDK for Java bindings
  - openjdk>=8
  
  # Development tools
  - pytest>=6.0.0
  - pytest-cov
  - flake8
  - black
  - jupyter
  
  # Documentation
  - sphinx
  - sphinx_rtd_theme
  
  # Optional dependencies for examples
  - scikit-learn>=1.0.0
  - plotly>=5.3.0
  
  # Additional pip packages
  - pip:
    - pytest-benchmark>=3.4.0
    - memory-profiler>=0.60.0