/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cudclusterplus_CuDClusterPlusJNI */

#ifndef _Included_com_cudclusterplus_CuDClusterPlusJNI
#define _Included_com_cudclusterplus_CuDClusterPlusJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cudclusterplus_CuDClusterPlusJNI
 * Method:    dbscan
 * Signature: ([FIIFI[I)I
 */
JNIEXPORT jint JNICALL Java_com_cudclusterplus_CuDClusterPlusJNI_dbscan
  (JNIEnv *, jclass, jfloatArray, jint, jint, jfloat, jint, jintArray);

/*
 * Class:     com_cudclusterplus_CuDClusterPlusJNI
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cudclusterplus_CuDClusterPlusJNI_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif